dependencies:
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: import-app-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- name: jx-app-ui
  repository: http://chartmuseum.jenkins-x.io
  version: 0.1.26
- name: jx-java-example-app
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
